language: java
sudo: false

jdk:
- openjdk8

install:

- mvn clean install -B -V

script:
- sh ./check_format.sh

after_success:
- bash <(curl -s https://codecov.io/bash) -t 71dff73a-664a-437b-9c46-8ef93fe7520d